version: "3.5"

services:
  curupira:
    container_name: curupira
    image: dwcorp/curupira:latest
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - ISSUER=${ISSUER:-http://localhost:8080}
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-authdb}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN:-.dwcorp.com.br}
      - SESSION_SECRET=${SESSION_SECRET}
      - DEFAULT_ACCESS_TTL_SECS=${DEFAULT_ACCESS_TTL_SECS:-3600}
      - DEFAULT_REFRESH_TTL_MINS=${DEFAULT_REFRESH_TTL_MINS:-43200}
      - REQUIRE_API_KEY=${REQUIRE_API_KEY:-true}
    ports:
      - "${APP_PORT:-8080}:8080"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres_container
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-authdb}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      # Optional: Add init script to ensure database exists
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-authdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    # 6CSr~X5Cre3kHuT master key
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-3000}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
